// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {console} from "forge-std/console.sol";
import {IERC20} from "forge-std/interfaces/IERC20.sol";
import {IHooks} from "v4-core/src/interfaces/IHooks.sol";
import {Hooks} from "v4-core/src/libraries/Hooks.sol";
import {PoolKey} from "v4-core/src/types/PoolKey.sol";
import {Currency} from "v4-core/src/types/Currency.sol";
import {ParityPool} from "../src/ParityPool.sol";
import {ParityLP} from "../src/ParityLP.sol";
import {StETH} from "../src/StETH.sol";
import {Fixtures} from "./utils/Fixtures.sol";

contract RebaseYieldDistributionTest is Test, Fixtures {
    ParityPool hook;
    ParityLP lpToken;
    StETH stETH;

    function setUp() public {
        deployFreshManagerAndRouters();
        deployMintAndApprove2Currencies();
        deployAndApprovePosm(manager);

        // Deploy StETH as currency1 for rebasing tests
        stETH = new StETH();
        currency1 = Currency.wrap(address(stETH));

        address flags = address(
            uint160(Hooks.BEFORE_SWAP_FLAG | Hooks.BEFORE_SWAP_RETURNS_DELTA_FLAG | Hooks.BEFORE_ADD_LIQUIDITY_FLAG)
                ^ (0x4448 << 144)
        );
        bytes memory constructorArgs = abi.encode(manager, address(0x999)); // treasury address
        deployCodeTo("ParityPool.sol:ParityPool", constructorArgs, flags);
        hook = ParityPool(flags);
        lpToken = hook.LP_TOKEN();

        key = PoolKey(currency0, currency1, 3000, 60, IHooks(hook));
        manager.initialize(key, SQRT_PRICE_1_1);

        // Mint some stETH for testing
        stETH.mint(address(this), 10000e18);
        stETH.approve(address(hook), type(uint256).max);
    }

    function test_rebaseYieldDistribution_basicDistribution() public {
        uint256 liquidityAmount = 1000e18;

        // LP adds liquidity
        IERC20(Currency.unwrap(currency0)).approve(address(hook), liquidityAmount);
        hook.addLiquidity(key, liquidityAmount);

        // Check initial pool balances
        uint256 initialETHBalance = hook.poolETHBalance();
        uint256 initialStETHBalance = hook.poolStETHBalance();
        uint256 initialLastKnown = hook.lastKnownStETHBalance();
        uint256 poolManagerBalance = manager.balanceOf(address(hook), currency1.toId());

        console.log("Initial pool ETH balance:", initialETHBalance);
        console.log("Initial pool stETH balance:", initialStETHBalance);
        console.log("Initial last known stETH balance:", initialLastKnown);
        console.log("PoolManager balance for hook:", poolManagerBalance);

        // Check fees before rebasing
        (uint256 feesBefore0, uint256 feesBefore1) = hook.getTotalAccumulatedFees();

        // Simulate time passing to trigger rebasing
        vm.warp(block.timestamp + 365 days); // 1 year = ~5% yield

        // Check stETH balances before rebase
        uint256 poolManagerStETHBalance = stETH.balanceOf(address(manager));
        uint256 totalStETHSupply = stETH.totalSupply();
        console.log("PoolManager stETH balance before rebase:", poolManagerStETHBalance);
        console.log("Total stETH supply before rebase:", totalStETHSupply);

        // Manually trigger the stETH rebase (in real world this happens automatically)
        uint256 yieldGenerated = stETH.rebase();
        console.log("Yield generated by rebase:", yieldGenerated);

        // Check stETH balances after rebase
        poolManagerStETHBalance = stETH.balanceOf(address(manager));
        totalStETHSupply = stETH.totalSupply();
        uint256 poolManagerInternalBalance = manager.balanceOf(address(hook), currency1.toId());
        console.log("PoolManager stETH balance after rebase:", poolManagerStETHBalance);
        console.log("PoolManager internal accounting for hook:", poolManagerInternalBalance);
        console.log("Total stETH supply after rebase:", totalStETHSupply);

        // Check balances before claiming
        uint256 userStETHBefore = stETH.balanceOf(address(this));

        // Trigger rebase yield distribution by calling claimFees (which has syncRebaseYield modifier)
        (uint256 claimedETH, uint256 claimedStETH) = hook.claimFees(key);

        // Check balances after claiming
        uint256 userStETHAfter = stETH.balanceOf(address(this));

        console.log("Fees before rebase (ETH, stETH):", feesBefore0, feesBefore1);
        console.log("Claimed fees (ETH, stETH):", claimedETH, claimedStETH);
        console.log("User stETH balance before:", userStETHBefore);
        console.log("User stETH balance after:", userStETHAfter);
        console.log("Rebasing yield received:", claimedStETH);

        // Should have received rebasing yield as claimed fees
        assertGt(claimedStETH, 0, "Should have received rebasing yield from claimFees");
        assertApproxEqAbs(userStETHAfter - userStETHBefore, claimedStETH, 1e15, "User balance should increase by claimed amount (tolerance: 0.001 ETH)");

        // Updated pool tracking should reflect rebasing
        uint256 newLastKnown = hook.lastKnownStETHBalance();
        assertGt(newLastKnown, initialLastKnown, "Last known balance should be updated after rebase");
    }

    function test_rebaseYieldDistribution_compounding() public {
        uint256 liquidityAmount = 1000e18;

        // LP adds liquidity
        IERC20(Currency.unwrap(currency0)).approve(address(hook), liquidityAmount);
        hook.addLiquidity(key, liquidityAmount);

        // First rebase period (6 months)
        vm.warp(block.timestamp + 182 days);
        stETH.rebase(); // Trigger stETH rebase
        hook.claimFees(key); // Trigger rebase yield distribution

        uint256 balanceAfterFirstRebase = lpToken.balanceOf(address(this));
        (uint256 feesAfterFirst0, uint256 feesAfterFirst1) = hook.getTotalAccumulatedFees();

        console.log("LP tokens after first rebase:", balanceAfterFirstRebase);
        console.log("Fees after first rebase (ETH, stETH):", feesAfterFirst0, feesAfterFirst1);

        // Second rebase period (another 6 months) - yield should compound
        vm.warp(block.timestamp + 182 days);
        stETH.rebase(); // Trigger second stETH rebase
        hook.claimFees(key); // Trigger second rebase yield distribution

        (uint256 feesAfterSecond0, uint256 feesAfterSecond1) = hook.getTotalAccumulatedFees();

        console.log("Fees after second rebase (ETH, stETH):", feesAfterSecond0, feesAfterSecond1);
        console.log("Additional yield from compounding:", feesAfterSecond1 - feesAfterFirst1);

        // The second rebase should generate yield on the previous yield (compounding)
        uint256 firstYield = feesAfterFirst1;
        uint256 secondYield = feesAfterSecond1 - feesAfterFirst1;

        assertGt(firstYield, 0, "First rebase should generate yield");
        assertGt(secondYield, 0, "Second rebase should generate additional yield");

        // Second yield should be larger due to compounding effect
        // (yield is generated on larger stETH balance that includes previous yield)
        console.log("First yield:", firstYield);
        console.log("Second yield:", secondYield);
    }

    function test_rebaseYieldDistribution_multipleLPs() public {
        uint256 liquidityAmount1 = 1000e18;
        uint256 liquidityAmount2 = 500e18;

        // First LP adds liquidity
        IERC20(Currency.unwrap(currency0)).approve(address(hook), liquidityAmount1);
        hook.addLiquidity(key, liquidityAmount1);
        uint256 lpTokens1 = lpToken.balanceOf(address(this));

        // Second LP adds liquidity
        address secondLP = address(0x123);
        deal(Currency.unwrap(currency0), secondLP, liquidityAmount2);
        deal(address(stETH), secondLP, liquidityAmount2);

        vm.startPrank(secondLP);
        IERC20(Currency.unwrap(currency0)).approve(address(hook), liquidityAmount2);
        stETH.approve(address(hook), liquidityAmount2);
        hook.addLiquidity(key, liquidityAmount2);
        uint256 lpTokens2 = lpToken.balanceOf(secondLP);
        vm.stopPrank();

        // Simulate rebasing
        vm.warp(block.timestamp + 365 days);
        stETH.rebase(); // Trigger stETH rebase

        // Check pending fees before claiming (includes rebasing yield)
        (uint256 pending1_0, uint256 pending1_1) = hook.pendingFees(address(this));
        (uint256 pending2_0, uint256 pending2_1) = hook.pendingFees(secondLP);

        console.log("LP1 pending fees after rebase (ETH, stETH):", pending1_0, pending1_1);
        console.log("LP2 pending fees after rebase (ETH, stETH):", pending2_0, pending2_1);
        console.log("LP1 tokens:", lpTokens1, "LP2 tokens:", lpTokens2);

        // Yield should be distributed proportionally to LP token ownership
        uint256 totalLPTokens = lpTokens1 + lpTokens2;
        uint256 expectedRatio1 = (lpTokens1 * 1000) / totalLPTokens; // LP1's share * 1000
        uint256 expectedRatio2 = (lpTokens2 * 1000) / totalLPTokens; // LP2's share * 1000

        uint256 totalYield = pending1_1 + pending2_1;
        if (totalYield > 0) {
            uint256 actualRatio1 = (pending1_1 * 1000) / totalYield;
            uint256 actualRatio2 = (pending2_1 * 1000) / totalYield;

            console.log("Expected ratio1:", expectedRatio1, "Actual ratio1:", actualRatio1);
            console.log("Expected ratio2:", expectedRatio2, "Actual ratio2:", actualRatio2);

            // Allow 1% tolerance for rounding
            assertApproxEqRel(actualRatio1, expectedRatio1, 1e16, "LP1 should get proportional yield");
            assertApproxEqRel(actualRatio2, expectedRatio2, 1e16, "LP2 should get proportional yield");
        }
    }

    function skip_test_rebaseYieldDistribution_automaticOnSwap() public {
        uint256 liquidityAmount = 1000e18;

        // LP adds liquidity
        IERC20(Currency.unwrap(currency0)).approve(address(hook), liquidityAmount);
        hook.addLiquidity(key, liquidityAmount);

        // Simulate time passing
        vm.warp(block.timestamp + 182 days); // 6 months

        // Trigger stETH rebase
        stETH.rebase();

        // Check fees before swap
        (uint256 feesBefore0, uint256 feesBefore1) = hook.getTotalAccumulatedFees();

        // Approve tokens for swap
        IERC20(Currency.unwrap(currency1)).approve(address(swapRouter), 100e18);

        // Perform a swap - this should automatically trigger rebase yield distribution
        uint256 swapAmount = 100e18;
        swap(key, false, -int256(swapAmount), ZERO_BYTES);

        // Check fees after swap
        (uint256 feesAfter0, uint256 feesAfter1) = hook.getTotalAccumulatedFees();

        console.log("Fees before swap (ETH, stETH):", feesBefore0, feesBefore1);
        console.log("Fees after swap (ETH, stETH):", feesAfter0, feesAfter1);

        // Should have both trading fees and rebasing yield
        uint256 totalFeeIncrease = feesAfter1 - feesBefore1;

        assertGt(totalFeeIncrease, 0, "Should have accumulated both trading fees and rebasing yield");

        // The increase should be more than just the trading fee would be
        // (since it includes rebasing yield from 6 months)
        console.log("Total fee increase:", totalFeeIncrease);
    }

    function test_rebaseYieldDistribution_event() public {
        uint256 liquidityAmount = 1000e18;

        // LP adds liquidity
        IERC20(Currency.unwrap(currency0)).approve(address(hook), liquidityAmount);
        hook.addLiquidity(key, liquidityAmount);

        // Simulate rebasing
        vm.warp(block.timestamp + 365 days);
        stETH.rebase(); // Trigger stETH rebase

        // Should emit RebaseYieldDistributed event
        vm.expectEmit(false, false, false, false); // Don't check specific values, just that event is emitted
        emit RebaseYieldDistributed(0, 0); // Placeholder values

        hook.claimFees(key);
    }

    event RebaseYieldDistributed(uint256 yieldAmount, uint256 timestamp);
}